package com.ehens86.bet.ncaa_fb_sb_odds_parse_api.enums;

public enum PlayerStatIdEnum {
	RUSHING_VISITING, PASSING_VISITING, RECEIVING_VISITING, KICKING_VISITING, PUNTING_VISITING, PUNT_RETURNS_VISITING,
	KICK_RETURNS_VISITING, DEFENSE_VISITING, RUSHING_HOME, PASSING_HOME, RECEIVING_HOME, KICKING_HOME, PUNTING_HOME,
	PUNT_RETURNS_HOME, KICK_RETURNS_HOME, DEFENSE_HOME;

}
